-- MySQL Script generated by MySQL Workbench
-- Wed Sep 29 19:46:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema groupproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema groupproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `groupproject` DEFAULT CHARACTER SET utf8 ;
USE `groupproject` ;

-- -----------------------------------------------------
-- Table `groupproject`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupproject`.`User` (
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `time_created` DATE NOT NULL,
  `title` VARCHAR(20) NULL,
  `role` VARCHAR(20) NULL,
  `icon_url` VARCHAR(128) NULL,
  PRIMARY KEY (`user_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupproject`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupproject`.`Project` (
  `project_id` VARCHAR(45) ,
  `owner` VARCHAR(45) NOT NULL,
  `time_created` DATE NOT NULL,
  PRIMARY KEY (`project_id`),
  INDEX `user_fk_idx` (`owner` ASC) VISIBLE,
  CONSTRAINT `user_fk`
    FOREIGN KEY (`owner`)
    REFERENCES `groupproject`.`User` (`user_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupproject`.`Project_Columns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupproject`.`Project_Columns` (
  `column_id` VARCHAR(45) NOT NULL,
  `project_id` VARCHAR(45) NOT NULL,
  `column_name` VARCHAR(16) NOT NULL,
  `type` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`column_id`),
  INDEX `ProjectID_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `ProjectID`
    FOREIGN KEY (`project_id`)
    REFERENCES `groupproject`.`Project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupproject`.`Resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupproject`.`Resource` (
  `resource_id` VARCHAR(45) ,
  `time_created` DATE NOT NULL,
  PRIMARY KEY (`resource_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupproject`.`Project_Resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupproject`.`Project_Resources` (
  `record_id` VARCHAR(45) ,
  `project_id` VARCHAR(45) NOT NULL,
  `resource_id` VARCHAR(45) NOT NULL,
  `time_created` DATE NOT NULL,
  PRIMARY KEY (`record_id`),
  INDEX `ProjectID_idx` (`project_id` ASC) VISIBLE,
  INDEX `ResourceID_idx` (`resource_id` ASC) VISIBLE,
  CONSTRAINT `ProjectID_fk_2`
    FOREIGN KEY (`project_id`)
    REFERENCES `groupproject`.`Project` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ResourceID`
    FOREIGN KEY (`resource_id`)
    REFERENCES `groupproject`.`Resource` (`resource_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupproject`.`Resource_Details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupproject`.`Resource_Details` (
  `detail_id` VARCHAR(45) NOT NULL,
  `column_id` VARCHAR(45) NOT NULL,
  `resource_id` VARCHAR(45) NOT NULL,
  `detail_value` VARCHAR(20) NULL,
  `time_created` DATE NOT NULL,
  PRIMARY KEY (`detail_id`),
  INDEX `Resource_fk_idx` (`resource_id` ASC) VISIBLE,
  INDEX `column_fk_idx` (`column_id` ASC) VISIBLE,
  CONSTRAINT `Resource_fk`
    FOREIGN KEY (`resource_id`)
    REFERENCES `groupproject`.`Resource` (`resource_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `column_fk`
    FOREIGN KEY (`column_id`)
    REFERENCES `groupproject`.`Project_Columns` (`column_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
